import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { services, framework, whyFbc } from "@/lib/data";
import { Reveal } from "@/components/Reveal";
import { SectionHeading } from "@/components/SectionHeading";

const process = [["01", "Discover", "Understand business, audience, goals and current digital gaps."], ["02", "Build", "Create the website, app, brand assets or digital systems required."], ["03", "Launch", "Deploy, connect analytics, set up campaigns and activate customer channels."], ["04", "Grow", "Optimize content, ads, SEO, conversions and technology through ongoing support."]];

export default function Home() {
  return <>
    <section className="hero"><div className="container hero-content"><Reveal><span className="eyebrow">IT · DIGITAL · BRAND · GROWTH</span><h1>Technology and digital growth solutions for businesses ready to <em>build, brand and become.</em></h1><p className="hero-sub">A single partner for technology, digital presence and growth execution.</p><div className="actions"><Link className="button button-gold" href="/contact">Start a project <ArrowUpRight size={16} /></Link><a className="button button-quiet" href="https://wa.me/91XXXXXXXXXX" target="_blank">Chat on WhatsApp <span>↗</span></a></div></Reveal></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="01 · Company" title="Digital work should move the business forward." /><div className="three-col"><Reveal><div className="info-cell"><h3>Who we are</h3><p>FBC IT is the technology and digital-solutions arm of Founders Branding Club, focused on helping businesses establish a credible digital presence and convert it into growth.</p></div></Reveal><Reveal delay={.08}><div className="info-cell"><h3>What we do</h3><p>We combine web development, mobile applications, digital marketing, branding and ongoing digital support into practical business solutions.</p></div></Reveal><Reveal delay={.16}><div className="info-cell"><h3>Where we play</h3><p>Startups, founders, MSMEs, local businesses, professional services, D2C brands and growing companies across India.</p></div></Reveal></div></div></section>
    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="02 · The framework" title="One relationship. Three ways to create momentum." /><div className="framework">{framework.map((item, i) => <Reveal key={item.label} delay={i*.08}><div className="framework-card"><strong>{item.label}</strong><h3>{item.title}</h3><p>{item.text}</p></div></Reveal>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="03 · The gap" title="Many businesses have digital tools, but not a connected digital growth system." /><div className="four-grid">{[["01", "Fragmented vendors", "Website from one provider, marketing from another, design from another, creating delays and inconsistent execution."], ["02", "Weak digital presence", "Social pages without a high-converting website, strong brand system or clear customer journey."], ["03", "Tech complexity", "Technology without the burden of managing developers, tools, hosting, integrations and updates alone."], ["04", "Unmeasured marketing", "Content and advertising with activity but no clear lead, enquiry or conversion path."]].map(([n,t,p],i)=><Reveal delay={i*.06} key={n}><div className="info-cell problem-card"><span>{n}</span><h3>{t}</h3><p>{p}</p></div></Reveal>)}</div></div></section>
    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="04 · Our approach" title="From first conversation to useful, measurable momentum." /><div className="process">{process.map(([n,t,p])=><div className="process-step" key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div><p className="outcome">Outcome: a consistent digital ecosystem instead of disconnected activities.</p></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="05 · Capabilities" title="The right mix of digital capability for the next stage." /><div className="service-grid">{services.map((service,i)=>{const Icon=service.icon;return <Reveal key={service.slug} delay={i*.04}><Link href={`/services#${service.slug}`} className="service-card"><Icon className="service-icon" size={22}/><h3>{service.title}</h3><p>{service.short}</p><span className="service-link">Explore ↗</span></Link></Reveal>})}</div><div className="actions" style={{marginTop:35}}><Link className="button button-quiet" href="/services">View all services <ArrowUpRight size={16}/></Link></div></div></section>
    <section className="section section-alt"><div className="container"><SectionHeading eyebrow="06 · Why FBC IT" title="A practical partner for ambitious businesses." /><div className="six-grid">{whyFbc.map(([title,text],i)=><Reveal key={title} delay={i*.04}><div className="why-card"><h3>{title}</h3><p>{text}</p></div></Reveal>)}</div></div></section>
    <section className="section" style={{paddingTop:0}}><div className="container stat-bar"><div className="stat"><strong>60M+</strong><span>small businesses in India</span><small>Source: Meta, 2025</small></div><div className="stat"><strong>67%</strong><span>MSMEs showing digital readiness</span><small>Source: CMR, 2025</small></div><div className="stat"><strong>62%</strong><span>MSMEs seeking digital advisory</span><small>Source: CMR, 2025</small></div><div className="stat"><strong>13%</strong><span>MSMEs using digital marketing</span><small>Source: SIDBI / YourStory, 2025</small></div></div></section>
    <section className="cta-band"><div className="container"><span className="eyebrow">Ready when you are</span><h2>Let's build what's next.</h2><p>Technology · Branding · Digital Growth</p><Link className="button button-gold" href="/contact">Start a project <ArrowUpRight size={16}/></Link></div></section>
  </>;
}
